GET https://localhost:7162/api/producto HTTP/1.1
Accept: application/json

GET https://localhost:7162/api/producto/1 HTTP/1.1
Accept: application/json

POST https://localhost:7162/api/producto HTTP/1.1
Content-Type: application/json
Accept: application/json

GET https://gorest.co.in/public/v2/users HTTP/1.1

POST https://gorest.co.in/public/v2/users HTTP/1.1